# Generated by Django 5.0.6 on 2024-07-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_question_question_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image_link',
        ),
    ]
