# Generated by Django 5.0.6 on 2024-06-25 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания вопроса'),
        ),
    ]
