# Generated by Django 5.0.6 on 2024-06-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_superquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='superquestion',
            name='question_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
